# Generated by Django 2.0 on 2019-08-07 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20190805_0058'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default='')),
                ('update_dec', models.CharField(max_length=500)),
                ('update_timesup', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
