# Generated by Django 2.0 on 2019-08-10 10:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_orderupdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderupdate',
            old_name='update_timesup',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='orderupdate',
            name='update_dec',
        ),
        migrations.AddField(
            model_name='orderupdate',
            name='update_desc',
            field=models.CharField(default=django.utils.timezone.now, max_length=5000),
            preserve_default=False,
        ),
    ]
